sonar.projectKey=koodauspaja_footy-trends
sonar.organization=koodauspaja

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

# Exclude generated files and config from analysis
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**/*.spec.ts